### ISSUE TITLE
Dev script

### ISSUE THREAD

**Issue by valentin30** [ManiacMaxo/cra-template#3]
https://github.com/ManiacMaxo/cra-template/blob/aceb25a11f05a6942b91f7f306cc05024f7c6ef4/template.json#L16-L19

Add a dev script with hot reload

**Comment by ManiacMaxo** [comment]
a what?

**Comment by valentin30** [comment]
Script for development.
`"start": "react-scripts start"`

**Comment by ManiacMaxo** [comment]
these are built in when using CRA

**Comment by valentin30** [comment]
cool look your other issues
